#!/usr/bin/env ruby

def dependencies_satisfied?
  `bundle check`
end

def start_server
  exec("bundle exec jekyll serve")
end

def install_dependencies
  `bundle install`
end

if dependencies_satisfied?
  start_server
else
  puts "Missing some dependendies."
  puts "Now running `bundle` to try to install them"
  if install_dependencies
    puts "Dependencies installed 🙌"
    puts "Now starting server"
    start_server
  else
    puts "a bad happend :("
  end
end